package com.model;

/**
 * TKeshi generated by MyEclipse Persistence Tools
 */

public class TKeshi implements java.io.Serializable
{


	private Integer keshiId;
	private String keshiAnme;
	private String del;
	
	private int keshixiayisheng;

	public String getDel()
	{
		return del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

	public String getKeshiAnme()
	{
		return keshiAnme;
	}

	public void setKeshiAnme(String keshiAnme)
	{
		this.keshiAnme = keshiAnme;
	}

	public Integer getKeshiId()
	{
		return keshiId;
	}

	public void setKeshiId(Integer keshiId)
	{
		this.keshiId = keshiId;
	}

	public int getKeshixiayisheng()
	{
		return keshixiayisheng;
	}

	public void setKeshixiayisheng(int keshixiayisheng)
	{
		this.keshixiayisheng = keshixiayisheng;
	}

}